# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MKDoc-Text-Structured
version:      0.82
version_from: lib/MKDoc/Text/Structured.pm
installdirs:  site
requires:
    Scalar::Util:                  1.07
    Test::More:                    0.47
    URI::Find:                     0.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
